### PR TITLE
Better QFT Compilation python prototyping

### PR DESCRIPTION
**Pull request by isolatedinformation**
This PR solves #263 of Better QFT compilation in the Pauli Formalism
- Partitions a long gate sequence to strings that can be compressed as a single Pauli rotation (`gates/compress_rotation_approximations.py`)
For instance, processing the gate with phase = `pi/2^100`  gives the following, where each partition is one PauliRotation gate:
```bash
The number of partitions is 466
The number of gates is 1172
```
- incorporate the compression in `PauliRotation`
- [x] Testing
	- [x] 	`partition_gate_sequence`
	- [x] `to_basic_form_approximation_and_compression`

### CODE REVIEW

**Comment by isolatedinformation** [comment]
@gwwatkin Do we want to cache the PauliFrame rotations also? A lot of the sequences are either `HSTH` or `HTH`!

**Comment by isolatedinformation** [comment]
compression_X_rotations


compression_Z_rotations

**Review by gwwatkin — APPROVED** [review]
Can't go too thoroughly right now but ok with merging to go ahead since it doesn't affect the main pipeline.

We need to check thas LLOPs work as expected with unusual rotations like 5pi/8

Could you remove the images from the assets and then do a use the squash merge button? It's so we don use up the git history space with files. You can add the images to the PR on github.

**Comment by isolatedinformation** [comment]
Done! I will raise an issue for the LLOPS checking

**Pull request merged**
