### PR TITLE
Add submodue instructions to contributing guide

### PR DESCRIPTION
**Pull request by gwwatkin**
As noted by @Keelando [in this comment](https://github.com/latticesurgery-com/lattice-surgery-compiler/issues/230#issuecomment-1028455222), useful to new contributors.

### CODE REVIEW

**Review by alexnguyenn — APPROVED** [review]

**Comment by Keelando** [comment]
Git keeps asking me to about untracked changes in the Opensurgery submodule after updating. How do we stop that?  @gwwatkin

**Comment by gwwatkin** [comment]
> Git keeps asking me to about untracked changes in the Opensurgery submodule after updating. How do we stop that? @gwwatkin

@Keelando not sure ... does it to me too

**Comment by gwwatkin** [comment]
@Keelando maybe this? https://stackoverflow.com/questions/5126765/how-to-get-rid-of-git-submodules-untracked-status

**Comment by Keelando** [comment]
Some viable options there. Would be nice to standardize so that contributors all have the identical environment.

**Review by Keelando — APPROVED** [review]

**Comment by gwwatkin** [comment]
> Some viable options there. Would be nice to standardize so that contributors all have the identical environment.

@Keelando you are welcom to open a pr

**Pull request merged**
