### PR TITLE
Adding codecov

### LINKED ISSUE #123: Adding codecov
To be done after: https://github.com/latticesurgery-com/lattice-surgery-compiler/issues/100.

### PR DESCRIPTION
**Pull request by alexnguyenn**
Closes: #123 

~~Work in progress~~. Ready for merging. Changes:
* Adding [pytest-cov](https://pypi.org/project/pytest-cov/)
* Add an job to upload the coverage report generated by `pytest-cov` to codecov.io. This will be triggered upon completion of testing.

### CODE REVIEW

**Comment by alexnguyenn** [comment]
Extra note that coverage report is generated on Python 3.9 and only uploaded to codecov on the main repository - not forks.

**Comment by alexnguyenn** [comment]
Was wondering how did we get 50%+ coverage 🤣. It is fixed now

**Comment by gwwatkin** [comment]
Can't see the report though, do I need to regenerate it somehow ?
Screenshot_20211121_193233

**Comment by alexnguyenn** [comment]
@gwwatkin weird it went missing for me too - might be because we don't have a base report yet. I am re-running the job now

**Review by gwwatkin — APPROVED** [review]
Configs make sense, might be best to debug this with live PRs since it's non critical

**Comment by gwwatkin** [comment]
Codecov seems to be working fine

**Pull request merged**
