### PR TITLE
PauliOpCircuit equality

### PR DESCRIPTION
**Pull request by isolatedinformation**
-  added equality and not equal  of PauliOpCircuit
- added tests for PauliOpCircuit equality

### CODE REVIEW

**Review by gwwatkin — APPROVED** [review]
Should be good. I would wait for #148 to go in first so we can test the CI

**Comment by alexnguyenn** [comment]
Just minor stuffs but I think we would need at least 3 test cases for each functions (as we have multiple checks in `__eq__`).

**Comment by isolatedinformation** [comment]
Aren't there 3 test cases for both functions? I made three different circuits, all the things are checked for.

**Comment by alexnguyenn** [comment]
oh mb I missed that. I see how it works now

**Pull request merged**
