### PR TITLE
[BUG-FIX] T Gate missng in RZ Gate definition

### PR DESCRIPTION
**Pull request by isolatedinformation**
Issue Description
-----------------

For both `Fraction(1,2)` and `Fraction(1,4)`, the `to_clifford_plus_t()` method decomposes the `RZ` rotation to the S gate for both the fractions, instead of decomposing to the S and T gates respectively. This PR fixes this :) 

How to Reproduce
----------------

### Code Snippet

```python
TEST_RZ_GATE = """OPENQASM 2.0;
include "qelib1.inc";
qreg q0[4];
h q0[3];
barrier q0[0],q0[1],q0[2],q0[3];
rz(pi/2) q0[1];
rz(pi/4) q0[0];
"""


circ = GatesCircuit().from_qasm(TEST_RZ_GATE)
print("Gate Sequence before conversion to Clifford+T")
for gate in circ.gates:
    print(gate)
print("\nGate sequence after conversion to Clifford T ")
for gate in circ.to_clifford_plus_t().gates:
    print(gate)
```

### Error Output

```
Gate Sequence before conversion to Clifford+T
H(target_qubit=3)
RZ(target_qubit=1, phase=Fraction(1, 2))
RZ(target_qubit=0, phase=Fraction(1, 4))

Gate sequence after conversion to Clifford T
H(target_qubit=3)
S(target_qubit=1)
S(target_qubit=0)
```

### Corrected Output (in this pr)
```
Gate Sequence before conversion to Clifford+T
H(target_qubit=3)
RZ(target_qubit=1, phase=Fraction(1, 2))
RZ(target_qubit=0, phase=Fraction(1, 4))

Gate sequence after conversion to Clifford T
H(target_qubit=3)
S(target_qubit=1)
T(target_qubit=0)

```

### CODE REVIEW

**Comment by isolatedinformation** [comment]
So  pytest did not pick this up as an error because the test classes were defined with the name `GateTest` instead of`TestGate` 
https://stackoverflow.com/questions/34363388/pytest-no-tests-ran! Added fixes for the tests also

**Comment by isolatedinformation** [comment]
@gwwatkin @alexnguyenn The test actions for pytest did not run properly for this! I stopped it after it ran for  20 minutes

**Comment by gwwatkin** [comment]
@isolatedinformation did you run `pytest --update-snapshot`?

**Comment by gwwatkin** [comment]
And yes we need to fix this, when certain long snapshots don't match it seems to hang, but that is the whole point of snapshot tests, they check for regressions.

@alexnguyenn can we set a timeout for a couple minutes?

**Comment by isolatedinformation** [comment]
yeah i did run to update the snapshot and tests ran locally, it just did not on the actions

**Comment by gwwatkin** [comment]
@isolatedinformation I think you need to commit the changes to the snapshot files, I don't see any of them changed in the diff

**Review by gwwatkin — APPROVED** [review]

**Pull request merged**
