### PR TITLE
 Fast Slice Composer in C++

### PR DESCRIPTION
**Pull request by gwwatkin**
Setup the `cmake`, `pybind` stack to build. Still have to make it usable from python's `lsqecc` but you can do a trivial test by cd`ing to the build directory an manually importing the complied shared object.

No functionality yet, but started thinking about data structures.

### CODE REVIEW

**Comment by alexnguyenn** [comment]
Just wondering can't you just `pip install pybind`?

**Comment by gwwatkin** [comment]
> Just wondering can't you just `pip install pybind`?

I tried, it is indeed possible to do it, but then you have to go chase down the header files from the venv and either add that to your include path or copy them to your project to make them work with the IDE. The pybind example using pip/setuptools is incompatible with CLion so we'd need a dual build system with cmake anyways.

**Comment by gwwatkin** [comment]
If I see we are making good progress with this experimental branch, I'll use a cleaner solution. I could set CMake to point to the the venv's site-packages with the headers so we can eliminate the need to have the submodule (note that that's the way they sugest to use [pybind11 with cmake](https://github.com/pybind/cmake_example)). And then schedule cmake to run after pybind is installed.

Another alternative might be Conan, that's how qiskit-aer manages c++ dependencies

**Comment by gwwatkin** [comment]
Something like Conan would be useful because we want to be able to add other packages like Eigen

**Comment by gwwatkin** [comment]
Moved to it's own repo [liblsqecc](https://github.com/latticesurgery-com/liblsqecc). We probably won't even need to interface python with the introduction of the LS Instruction format #246

**Comment by gwwatkin** [comment]
Though we might still want python bindings to expose as an API :thinking:

**Pull request closed without merging**
