### PR TITLE
Add tests for DependencyGraph

### LINKED ISSUE #172: Test `dependency_graph.py`
As title. Expected to be painful since I don't recall how I implemented it.

### PR DESCRIPTION
**Pull request by alexnguyenn**
Closes #172. Work in progress.

### CODE REVIEW

**Comment by alexnguyenn** [comment]
@gwwatkin: still have `from_list` and `from_circuit_by_commutation` left to write tests for. I am planning to use the example from #71 but any insight will be appreciated.

**Review by gwwatkin — APPROVED** [review]
@alexnguyenn I suggested in #172 putting this on pause, since it might be some time before we start using it. What's here is good. I propose we commit what we have and leave an "experimental" note in the docstring of the classes exported by this file.

If you want to proceed anyways, I think the case in 71 is good and I can help you come up with more. I'd be careful about writing tests for classes that are not involved yet in the main compilation. It might turn out that when we start to use the practically we'll have to make heavy changes.

**Comment by gwwatkin** [comment]
If you choose to merge you can just move #172 to the backlog

**Comment by alexnguyenn** [comment]
I think I will add the test case in #71 and then merge this - actually it might already be in `debug/` already.

**Comment by gwwatkin** [comment]
Sounds like a good plan. I might just consider a note that says experimental to the doctring

**Comment by alexnguyenn** [comment]
added the test case from #71 - I think I am done with this. Ran into some problems with PauliRotation being non-hashable (see #175).

**Pull request merged**
