### PR TITLE
Enable CORS in local api development server

### PR DESCRIPTION
**Pull request by gwwatkin**
Needed because of the different port of the web UI

### CODE REVIEW

**Comment by alexnguyenn** [comment]
Did you add anything to `requirements.txt`?

**Comment by gwwatkin** [comment]
> Did you add anything to `requirements.txt`?

Yes I did, good point. I added jsonpickle. Should have probably split the reformat commit and then adding the package

**Comment by gwwatkin** [comment]
Also just noticed that there are changes made by the `black` formatter

**Review by alexnguyenn — APPROVED** [review]

**Comment by alexnguyenn** [comment]
> > Did you add anything to `requirements.txt`?
> 
> Yes I did, good point. I added jsonpickle. Should have probably split the reformat commit and then adding the package

Yeah just need to keep track of that for setting up .cfg file for our project (though `jsonpickle` would go to dev part I think 🤔)

**Pull request merged**
